# Generated by Django 5.2.7 on 2026-03-08 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fix_all_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField(help_text='2048-dimensional feature vector from ResNet50')),
                ('model_version', models.CharField(default='ResNet50', help_text='Model used for feature extraction', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='products_re_product_439051_idx'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'recorded_at'], name='products_pr_product_045f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='productfeature',
            index=models.Index(fields=['product'], name='products_pr_product_d26951_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', 'viewed_at'], name='products_pr_user_id_80dce9_idx'),
        ),
    ]
